const $ = (id) => document.getElementById(id);
const charts = {};
const COLORS = { cream:'#f1eee4', muted:'#a7b5a7', lime:'#52e33d', orange:'#ff6528', line:'#436451', tool:'#9ba895', deep:'#ff6528', balanced:'#52e33d' };
const COPY = {
  zh: { overview:'总览',decisions:'选择依据',projects:'项目列表',decisionKicker:'可审计的模型选择',decisionsHeading:'为什么是这个模型？',decisionsNote:'从第一性原理出发：先减少问题规模，再用证据而不是模型名决定是否升级。',evidenceKicker:'六维证据',evidenceHeading:'自动路由前必须逐项满足',deepseekHeading:'按任务选择，而非按名称选择',officialApi:'官方 API',operationKicker:'执行边界',operationHeading:'手动、半自动与自动',overviewKicker:'Skill 使用成效',heroTitle:'使用 Skill 后，<br />项目少花多少？',projectsKicker:'已使用该 Skill 的项目',projectsTitle:'项目收益',howItWorks:'收益如何产生',methodOne:'先缩小任务与上下文范围',methodTwo:'工具验证优先，失败才升级',methodThree:'按项目价值分配推理预算',projectsHeading:'项目列表',projectsNote:'每项数据均为本地模拟演示，不代表通用性能结论。',footerNote:'耗时为端到端时长；成本为 API 等效估算。',projectsUsed:'个项目',before:'使用前',after:'使用 Skill 后',duration:'耗时',cost:'API 等效成本',saved:'节省',steps:'执行步骤',verified:'验证',pass:'通过',tool:'确定性工具',fast:'快速模型',balanced:'均衡模型',deep:'深度推理',simulated:'模拟数据',overviewDescription:'基于已完成项目的可验证对比：把高推理预算留给真正需要它的步骤。',actualDuration:'实际耗时',aggregateKicker:'综合数据',timeComposition:'模型策略与阶段耗时',efficiencyKicker:'成本 × 耗时',efficiencyTitle:'项目效率象限',savingKicker:'最节省项目',savingTitle:'项目节省变化',stepsKicker:'步骤与模型',stepsChartTitle:'最节省项目的执行路径',beforeSeries:'使用前',afterSeries:'使用 Skill 后',minutes:'分钟',durationAxis:'耗时（分钟）',costAxis:'API 等效成本（USD）',projectAxis:'项目',timeSaved:'节省耗时',tokenCostSaved:'API token 等效成本',costSaved:'成本节省',modelExecution:'模型执行',toolVerification:'工具验证',switching:'模型切换',approvalWaiting:'授权等待' },
  en: { overview:'Overview',decisions:'Decision basis',projects:'Projects',decisionKicker:'AUDITABLE MODEL SELECTION',decisionsHeading:'Why this model?',decisionsNote:'First principles: reduce the problem before deciding whether evidence warrants an upgrade.',evidenceKicker:'SIX EVIDENCE DIMENSIONS',evidenceHeading:'Every one must pass before automatic routing',deepseekHeading:'Choose for the task, not the name',officialApi:'Official API',operationKicker:'OPERATING BOUNDARIES',operationHeading:'Manual, semi-automatic, and automatic',overviewKicker:'SKILL IMPACT',heroTitle:'How much less<br />do projects spend?',projectsKicker:'PROJECTS USING THIS SKILL',projectsTitle:'Project impact',howItWorks:'HOW THE SAVINGS HAPPEN',methodOne:'Bound task scope and context first',methodTwo:'Validate with tools; escalate only on failure',methodThree:'Allocate reasoning budget by project value',projectsHeading:'Projects',projectsNote:'Every value is local simulated demo data, not a general performance claim.',footerNote:'Duration is end-to-end wall-clock time; cost is an API-equivalent estimate.',projectsUsed:'projects',before:'Before',after:'With Skill',duration:'Duration',cost:'API-equivalent cost',saved:'Saved',steps:'Execution steps',verified:'Validation',pass:'Passed',tool:'Deterministic tool',fast:'Fast model',balanced:'Balanced model',deep:'Deep reasoning',simulated:'Simulated data',overviewDescription:'A verified comparison across completed projects: reserve deeper reasoning for the steps that truly need it.',actualDuration:'Actual duration',aggregateKicker:'PORTFOLIO DATA',timeComposition:'Model strategy and phase duration',efficiencyKicker:'COST × TIME',efficiencyTitle:'Project efficiency quadrant',savingKicker:'MOST EFFICIENT PROJECT',savingTitle:'Project savings change',stepsKicker:'STEPS AND MODELS',stepsChartTitle:'Execution path of the most efficient project',beforeSeries:'Before',afterSeries:'With Skill',minutes:'minutes',durationAxis:'Duration (minutes)',costAxis:'API-equivalent cost (USD)',projectAxis:'Project',timeSaved:'Time saved',tokenCostSaved:'API-token equivalent cost',costSaved:'Cost saved',modelExecution:'Model execution',toolVerification:'Tool verification',switching:'Switching',approvalWaiting:'Approval wait' }
};
Object.assign(COPY.zh,{benchmarkKicker:'外部测评与项目验收',benchmarkHeading:'证据覆盖度，而非虚构总分',benchmarkNote:'图形反映证据是否已刷新、适用且经本项目验证；具体 benchmark 数值由刷新器和可选解析器填充。',sourceKicker:'可联网刷新',sourceHeading:'官方说明与独立测评来源'});
Object.assign(COPY.en,{benchmarkKicker:'EXTERNAL EVALUATION AND PROJECT ACCEPTANCE',benchmarkHeading:'Evidence coverage, not an invented score',benchmarkNote:'The chart shows whether evidence is fresh, applicable, and project-validated; concrete benchmark values are supplied by refreshers and optional parsers.',sourceKicker:'ONLINE REFRESH',sourceHeading:'Official documentation and independent evaluation sources'});
Object.assign(COPY.zh,{preferenceKicker:'路由偏好',preferenceHeading:'为这一次任务选择目标',preferenceIntro:'默认自动判断；速度与质量偏好只会在安全、能力和验收允许的范围内生效。'});
Object.assign(COPY.en,{preferenceKicker:'ROUTING PREFERENCE',preferenceHeading:'Choose the goal for this task',preferenceIntro:'Automatic is the default; speed and quality only apply within safety, capability, and acceptance constraints.'});
let language = new URLSearchParams(location.search).get('lang') || localStorage.getItem('model-router-language') || 'zh'; if (!COPY[language]) language='zh';
let data, preferenceMode='auto';
const t=(key)=>COPY[language][key]||key;
const money=(n)=>`$${n.toFixed(n < .1 ? 3 : 2)}`;
const minutes=(sec)=>`${(sec/60).toFixed(1)}m`;
const pct=(after,before)=>`${Math.round((1-after/before)*100)}%`;
function chart(id, option){charts[id]?.dispose();charts[id]=echarts.init($(id),null,{renderer:'canvas'});charts[id].setOption(option);}
function base(){return {animation:false,textStyle:{fontFamily:'Arial, Helvetica, sans-serif',color:COLORS.cream},tooltip:{confine:true,backgroundColor:'#061a10',borderColor:COLORS.line,textStyle:{color:COLORS.cream}},grid:{left:70,right:28,top:30,bottom:45,containLabel:true}};}
function applyLanguage(){document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=language==='zh'?'Model Router — Skill 项目收益':'Model Router — Skill impact';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));$('language-toggle').textContent=language==='zh'?'EN':'中文';$('language-toggle').setAttribute('aria-label',language==='zh'?'Switch to English':'切换到中文');if(data)render();}
function renderSummary(project){return `<a class="project-summary" href="#projects" data-project="${project.id}"><div><strong>${project.name[language]}</strong><span>${project.scope[language]}</span></div><div class="delta-pair"><span><small>${t('timeSaved')}</small><strong>−${pct(project.after.durationSec,project.before.durationSec)}</strong></span><span><small>${t('tokenCostSaved')}</small><strong>−${pct(project.after.costUsd,project.before.costUsd)}</strong></span></div></a>`;}
function renderCard(project){return `<article class="project-card panel" id="project-${project.id}"><header class="project-card-head"><div><p class="eyebrow">${t('simulated')}</p><h2>${project.name[language]}</h2><p>${project.description[language]}</p></div><span class="source-tag">${project.scope[language]}</span></header><div class="comparison"><div><span>${t('before')}</span><strong>${minutes(project.before.durationSec)}</strong><small>${money(project.before.costUsd)} ${t('cost')}</small></div><div class="comparison-arrow">→</div><div class="after"><span>${t('after')}</span><strong>${minutes(project.after.durationSec)}</strong><small>${money(project.after.costUsd)} ${t('cost')}</small></div><div class="savings"><span>${t('saved')}</span><strong>${pct(project.after.durationSec,project.before.durationSec)}<small>${t('duration')}</small></strong><strong>${pct(project.after.costUsd,project.before.costUsd)}<small>${t('cost')}</small></strong></div></div><div class="steps"><div class="steps-heading"><h3>${t('steps')}</h3><span>${t('verified')} · ${t('pass')}</span></div>${project.steps.map((step,index)=>`<div class="step"><span class="step-index">0${index+1}</span><div><strong>${step.title[language]}</strong><small>${step.scope[language]}</small></div><span class="tier ${step.tier}">${t(step.tier)}</span><span class="step-check">✓</span></div>`).join('')}</div></article>`;}
function renderProjectIndex(projects){return projects.map((project,index)=>`<button class="project-index-item${index===0?' is-active':''}" type="button" data-project-index="${project.id}"><span>${String(index+1).padStart(2,'0')}</span><strong>${project.name[language]}</strong><small>${project.scope[language]}</small></button>`).join('');}
function focusProject(projectId){const cards=$('project-cards'),target=$(`project-${projectId}`);if(!cards||!target)return;document.querySelectorAll('[data-project-index]').forEach(item=>item.classList.toggle('is-active',item.dataset.projectIndex===projectId));cards.scrollTo({top:target.offsetTop-cards.offsetTop,behavior:'smooth'});}
function renderDecisionFramework(){const framework=data.decisionFramework;if(!framework)return;$('decision-principles').innerHTML=framework.principles.map(item=>`<article class="panel"><p class="eyebrow">FIRST PRINCIPLE</p><h2>${item.title[language]}</h2><p>${item.detail[language]}</p></article>`).join('');$('evidence-snapshot').textContent=language==='zh'?`资料快照：${framework.snapshotAt}`:`Snapshot: ${framework.snapshotAt}`;$('evidence-dimensions').innerHTML=framework.dimensions.map(item=>`<article class="evidence-item"><strong>${item.title[language]}</strong><p>${item.detail[language]}</p></article>`).join('');$('deepseek-models').innerHTML=framework.deepseek.map(item=>`<div><small>${item.tier[language]}</small><strong>${item.model}</strong><p>${item.use[language]}<br><br>${item.checks[language]}</p></div>`).join('');$('operation-modes').innerHTML=framework.operationModes.map(item=>`<div><small>${item.mode[language]}</small><strong>${item.where[language]}</strong><p>${item.rule[language]}</p></div>`).join('');}
function renderPreferences(){const modes=data?.decisionFramework?.preferenceModes||[],selected=modes.find(mode=>mode.id===preferenceMode)||modes[0];if(!selected)return;$('preference-controls').innerHTML=modes.map(mode=>`<button type="button" class="preference-option${mode.id===selected.id?' is-active':''}" data-preference="${mode.id}" aria-pressed="${mode.id===selected.id}"><strong>${mode.title[language]}</strong><small>${mode.short[language]}</small></button>`).join('');$('preference-result').className=`preference-result preference-${selected.id}`;$('preference-result').innerHTML=`<div><h3>${selected.title[language]}</h3><p>${selected.detail[language]}<br><br>${selected.guardrail[language]}</p></div><div class="preference-stats">${selected.metrics[language].map(([label,value])=>`<div class="preference-stat"><small>${label}</small><strong>${value}</strong></div>`).join('')}</div>`;}
const renderDecisionFrameworkBase = renderDecisionFramework;
renderDecisionFramework = () => { renderDecisionFrameworkBase(); renderPreferences(); const framework=data.decisionFramework;if(!framework)return;const radar=framework.radar;if(radar&&window.echarts){const option=base();option.radar={indicator:radar.labels[language].map(name=>({name,max:100})),splitNumber:3,axisName:{color:COLORS.cream,fontSize:11},splitLine:{lineStyle:{color:COLORS.line}},splitArea:{areaStyle:{color:['rgba(82,227,61,.03)','rgba(82,227,61,.08)']}},axisLine:{lineStyle:{color:COLORS.line}}};option.series=[{type:'radar',data:[{value:radar.values,name:language==='zh'?'当前证据覆盖':'Current evidence coverage',areaStyle:{color:'rgba(82,227,61,.23)'},lineStyle:{color:COLORS.lime},itemStyle:{color:COLORS.lime}}]}];chart('evidence-radar',option);}$('evidence-sources').innerHTML=(framework.sources||[]).map(source=>`<article class="evidence-item"><strong><a href="${source.url}" target="_blank" rel="noreferrer">${source.name}</a></strong><p>${source.kind[language]}<br><br>${source.status[language]}</p></article>`).join('');$('operation-modes').innerHTML=(framework.operationModes||[]).map(item=>`<article><small>${item.mode[language]}</small><strong>${item.where[language]}</strong><p>${item.rule[language]}</p></article>`).join(''); };
function renderCharts(projects){
  const names=projects.map(p=>p.name[language]), before=projects.map(p=>p.before.durationSec/60), after=projects.map(p=>p.after.durationSec/60);
  let o=base();o.legend={bottom:0,textStyle:{color:COLORS.muted}};o.xAxis={type:'value',name:t('durationAxis'),nameTextStyle:{color:COLORS.muted},axisLabel:{color:COLORS.muted},splitLine:{lineStyle:{color:'#274936'}}};o.yAxis={type:'category',data:names,axisLabel:{color:COLORS.cream},axisTick:{show:false}};o.series=[{name:t('beforeSeries'),type:'bar',data:before,itemStyle:{color:COLORS.cream,borderRadius:[0,5,5,0]}},{name:t('afterSeries'),type:'bar',data:after,itemStyle:{color:COLORS.lime,borderRadius:[0,5,5,0]}}];chart('time-comparison',o);
  o=base();o.grid={left:55,right:30,top:30,bottom:50,containLabel:true};o.xAxis={type:'value',name:t('costAxis'),nameLocation:'middle',nameGap:30,nameTextStyle:{color:COLORS.muted,fontSize:10},axisLabel:{color:COLORS.muted},splitLine:{lineStyle:{color:'#274936'}}};o.yAxis={type:'value',name:t('durationAxis'),nameLocation:'middle',nameGap:36,nameTextStyle:{color:COLORS.muted,fontSize:10},axisLabel:{color:COLORS.muted},splitLine:{lineStyle:{color:'#274936'}}};o.series=[{type:'scatter',symbolSize:16,data:projects.flatMap(p=>[{name:`${p.name[language]} · ${t('before')}`,value:[p.before.costUsd,p.before.durationSec/60],itemStyle:{color:COLORS.cream}},{name:`${p.name[language]} · ${t('after')}`,value:[p.after.costUsd,p.after.durationSec/60],itemStyle:{color:COLORS.lime} }]),label:{show:true,position:'top',formatter:p=>p.data.name.split(' · ')[1],color:COLORS.cream,fontSize:10},labelLayout:{hideOverlap:true}}];chart('project-scatter',o);
  o=base();o.grid={left:112,right:24,top:24,bottom:58};o.xAxis={type:'category',data:[t('timeSaved'),t('costSaved')],axisLabel:{color:COLORS.muted}};o.yAxis={type:'category',data:names,axisLabel:{color:COLORS.cream,width:95,overflow:'truncate'},axisTick:{show:false}};o.visualMap={min:0,max:.7,calculable:false,orient:'horizontal',left:'center',bottom:0,textStyle:{color:COLORS.muted,fontSize:9},inRange:{color:['#385a40',COLORS.lime]}};o.series=[{type:'heatmap',data:projects.flatMap((p,y)=>[[0,y,1-p.after.durationSec/p.before.durationSec],[1,y,1-p.after.costUsd/p.before.costUsd]]),label:{show:true,color:COLORS.cream,formatter:p=>`${Math.round(p.value[2]*100)}%`},itemStyle:{borderColor:'#0b2a1b',borderWidth:4}}];chart('project-heat',o);
  const best=[...projects].sort((a,b)=>(a.after.costUsd/a.before.costUsd)-(b.after.costUsd/b.before.costUsd))[0], kinds={tool:COLORS.tool,fast:'#d8d3c5',balanced:COLORS.balanced,deep:COLORS.deep};o=base();o.grid={left:160,right:30,top:25,bottom:40,containLabel:true};o.xAxis={type:'value',name:t('minutes'),nameLocation:'middle',nameGap:28,nameTextStyle:{color:COLORS.muted,fontSize:10},axisLabel:{show:false},splitLine:{show:false}};o.yAxis={type:'category',data:best.steps.map(s=>s.title[language]),axisLabel:{color:COLORS.cream,width:140,overflow:'truncate'},axisTick:{show:false}};o.series=[{type:'custom',renderItem:(params,api)=>{const y=api.coord([0,api.value(0)])[1],x=api.coord([0,0])[0],w=api.size([api.value(1),0])[0],h=18;return {type:'rect',shape:{x,y:y-h/2,width:w,height:h,r:6},style:{fill:kinds[api.value(2)]}}},data:best.steps.map((s,i)=>[i,1+i*.58,s.tier]),encode:{x:1,y:0}}];chart('project-timeline',o);
}
function renderStrategyChart(){const strategies=data.strategies||[],o=base();o.grid={left:72,right:26,top:30,bottom:48,containLabel:true};o.xAxis={type:'value',axisLabel:{color:COLORS.muted,formatter:v=>`${Math.round(v/60)}m`},splitLine:{lineStyle:{color:'#274936'}}};o.yAxis={type:'category',data:strategies.map(s=>s.name[language]),axisLabel:{color:COLORS.cream},axisTick:{show:false}};const phases=[[t('modelExecution'),'modelSec',COLORS.lime],[t('toolVerification'),'toolSec',COLORS.cream],[t('switching'),'switchSec',COLORS.orange],[t('approvalWaiting'),'approvalWaitSec','#6d8d77']];o.series=phases.map(([name,key,color])=>({name,type:'bar',stack:'total',barWidth:19,itemStyle:{color,borderRadius:name===t('approvalWaiting')?[0,5,5,0]:0},data:strategies.map(s=>s[key]||0)}));o.legend={bottom:0,textStyle:{color:COLORS.muted,fontSize:10},itemWidth:11,itemHeight:11};chart('time-comparison',o);}
function render(){const projects=data.projects||[],strategies=data.strategies||[],baseline=strategies.find(s=>s.id==='fixed_deep'),router=strategies.find(s=>s.id==='router');$('overview-description').textContent=t('overviewDescription');$('overview-time').textContent=baseline&&router?`−${pct(router.durationSec,baseline.durationSec)}`:'—';$('overview-cost').textContent=baseline&&router?`−${pct(router.costUsd,baseline.costUsd)}`:'—';$('project-count').textContent=`${projects.length} ${t('projectsUsed')}`;$('project-summary-list').innerHTML=projects.map(renderSummary).join('');$('project-index-list').innerHTML=renderProjectIndex(projects);$('project-cards').innerHTML=projects.map(renderCard).join('');$('updated-at').textContent=language==='zh'?`数据生成：${data.generatedAt||'本地数据'} · ${t('simulated')}`:`Generated: ${data.generatedAt||'local data'} · ${t('simulated')}`;renderDecisionFramework();renderCharts(projects);renderStrategyChart();}
function showView(view){document.querySelectorAll('.view-panel').forEach(el=>el.classList.toggle('is-active',el.id===view));document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('is-active',el.dataset.view===view));setTimeout(()=>Object.values(charts).forEach(c=>c.resize()));}
document.querySelector('nav').addEventListener('click',event=>{const link=event.target.closest('[data-view]');if(!link)return;event.preventDefault();showView(link.dataset.view);});document.addEventListener('click',event=>{const option=event.target.closest('[data-preference]');if(option){preferenceMode=option.dataset.preference;renderPreferences();return;}const link=event.target.closest('[data-project]');if(!link)return;event.preventDefault();showView('projects');setTimeout(()=>focusProject(link.dataset.project));});document.addEventListener('click',event=>{const link=event.target.closest('[data-project-index]');if(link)focusProject(link.dataset.projectIndex);});$('language-toggle').addEventListener('click',()=>{language=language==='zh'?'en':'zh';localStorage.setItem('model-router-language',language);applyLanguage();});window.addEventListener('resize',()=>Object.values(charts).forEach(c=>c.resize()));window.addEventListener('hashchange',()=>showView(['projects','decisions'].includes(location.hash.slice(1))?location.hash.slice(1):'overview'));fetch('./sample-data.json').then(response=>response.json()).then(json=>{data=json;applyLanguage();showView(['projects','decisions'].includes(location.hash.slice(1))?location.hash.slice(1):'overview');}).catch(()=>{const direct=location.protocol==='file:';const message=language==='zh'?'本地文件模式会阻止读取示例数据。请通过本地服务打开。':'File mode blocks the sample-data request. Open through the local server.';$('overview-description').innerHTML=direct?`${message} <a href="http://127.0.0.1:8765/">http://127.0.0.1:8765/</a>`:'Unable to load local demo data.';});
