const $ = (id) => document.getElementById(id);
const charts = {};
const COLORS = { cream:'#f1eee4', muted:'#a7b5a7', lime:'#52e33d', orange:'#ff6528', line:'#436451', tool:'#9ba895', deep:'#ff6528', balanced:'#52e33d' };
const COPY = {
  zh: { overview:'总览',projects:'项目列表',overviewKicker:'Skill 使用成效',heroTitle:'使用 Skill 后，<br />项目少花多少？',projectsKicker:'已使用该 Skill 的项目',projectsTitle:'项目收益',howItWorks:'收益如何产生',methodOne:'先缩小任务与上下文范围',methodTwo:'工具验证优先，失败才升级',methodThree:'按项目价值分配推理预算',projectsHeading:'项目列表',projectsNote:'每项数据均为本地模拟演示，不代表通用性能结论。',footerNote:'耗时为端到端时长；成本为 API 等效估算。',projectsUsed:'个项目',before:'使用前',after:'使用 Skill 后',duration:'耗时',cost:'API 等效成本',saved:'节省',steps:'执行步骤',verified:'验证',pass:'通过',tool:'确定性工具',fast:'快速模型',balanced:'均衡模型',deep:'深度推理',simulated:'模拟数据',overviewDescription:'基于已完成项目的可验证对比：把高推理预算留给真正需要它的步骤。',actualDuration:'实际耗时',aggregateKicker:'综合数据',timeComposition:'模型策略与阶段耗时',efficiencyKicker:'成本 × 耗时',efficiencyTitle:'项目效率象限',savingKicker:'最节省项目',savingTitle:'项目节省变化',stepsKicker:'步骤与模型',stepsChartTitle:'最节省项目的执行路径',beforeSeries:'使用前',afterSeries:'使用 Skill 后',minutes:'分钟',durationAxis:'耗时（分钟）',costAxis:'API 等效成本（USD）',projectAxis:'项目',timeSaved:'节省耗时',tokenCostSaved:'API token 等效成本',costSaved:'成本节省',modelExecution:'模型执行',toolVerification:'工具验证',switching:'模型切换',approvalWaiting:'授权等待' },
  en: { overview:'Overview',projects:'Projects',overviewKicker:'SKILL IMPACT',heroTitle:'How much less<br />do projects spend?',projectsKicker:'PROJECTS USING THIS SKILL',projectsTitle:'Project impact',howItWorks:'HOW THE SAVINGS HAPPEN',methodOne:'Bound task scope and context first',methodTwo:'Validate with tools; escalate only on failure',methodThree:'Allocate reasoning budget by project value',projectsHeading:'Projects',projectsNote:'Every value is local simulated demo data, not a general performance claim.',footerNote:'Duration is end-to-end wall-clock time; cost is an API-equivalent estimate.',projectsUsed:'projects',before:'Before',after:'With Skill',duration:'Duration',cost:'API-equivalent cost',saved:'Saved',steps:'Execution steps',verified:'Validation',pass:'Passed',tool:'Deterministic tool',fast:'Fast model',balanced:'Balanced model',deep:'Deep reasoning',simulated:'Simulated data',overviewDescription:'A verified comparison across completed projects: reserve deeper reasoning for the steps that truly need it.',actualDuration:'Actual duration',aggregateKicker:'PORTFOLIO DATA',timeComposition:'Model strategy and phase duration',efficiencyKicker:'COST × TIME',efficiencyTitle:'Project efficiency quadrant',savingKicker:'MOST EFFICIENT PROJECT',savingTitle:'Project savings change',stepsKicker:'STEPS AND MODELS',stepsChartTitle:'Execution path of the most efficient project',beforeSeries:'Before',afterSeries:'With Skill',minutes:'minutes',durationAxis:'Duration (minutes)',costAxis:'API-equivalent cost (USD)',projectAxis:'Project',timeSaved:'Time saved',tokenCostSaved:'API-token equivalent cost',costSaved:'Cost saved',modelExecution:'Model execution',toolVerification:'Tool verification',switching:'Switching',approvalWaiting:'Approval wait' }
};
let language = new URLSearchParams(location.search).get('lang') || localStorage.getItem('model-router-language') || 'zh'; if (!COPY[language]) language='zh';
let data;
const t=(key)=>COPY[language][key]||key;
const money=(n)=>`$${n.toFixed(n < .1 ? 3 : 2)}`;
const minutes=(sec)=>`${(sec/60).toFixed(1)}m`;
const pct=(after,before)=>`${Math.round((1-after/before)*100)}%`;
function chart(id, option){charts[id]?.dispose();charts[id]=echarts.init($(id),null,{renderer:'canvas'});charts[id].setOption(option);}
function base(){return {animation:false,textStyle:{fontFamily:'Arial, Helvetica, sans-serif',color:COLORS.cream},tooltip:{confine:true,backgroundColor:'#061a10',borderColor:COLORS.line,textStyle:{color:COLORS.cream}},grid:{left:70,right:28,top:30,bottom:45,containLabel:true}};}
function applyLanguage(){document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=language==='zh'?'Model Router — Skill 项目收益':'Model Router — Skill impact';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));$('language-toggle').textContent=language==='zh'?'EN':'中文';$('language-toggle').setAttribute('aria-label',language==='zh'?'Switch to English':'切换到中文');if(data)render();}
function renderSummary(project){return `<a class="project-summary" href="#projects" data-project="${project.id}"><div><strong>${project.name[language]}</strong><span>${project.scope[language]}</span></div><div class="delta-pair"><span><small>${t('timeSaved')}</small><strong>−${pct(project.after.durationSec,project.before.durationSec)}</strong></span><span><small>${t('tokenCostSaved')}</small><strong>−${pct(project.after.costUsd,project.before.costUsd)}</strong></span></div></a>`;}
function renderCard(project){return `<article class="project-card panel" id="project-${project.id}"><header class="project-card-head"><div><p class="eyebrow">${t('simulated')}</p><h2>${project.name[language]}</h2><p>${project.description[language]}</p></div><span class="source-tag">${project.scope[language]}</span></header><div class="comparison"><div><span>${t('before')}</span><strong>${minutes(project.before.durationSec)}</strong><small>${money(project.before.costUsd)} ${t('cost')}</small></div><div class="comparison-arrow">→</div><div class="after"><span>${t('after')}</span><strong>${minutes(project.after.durationSec)}</strong><small>${money(project.after.costUsd)} ${t('cost')}</small></div><div class="savings"><span>${t('saved')}</span><strong>${pct(project.after.durationSec,project.before.durationSec)}<small>${t('duration')}</small></strong><strong>${pct(project.after.costUsd,project.before.costUsd)}<small>${t('cost')}</small></strong></div></div><div class="steps"><div class="steps-heading"><h3>${t('steps')}</h3><span>${t('verified')} · ${t('pass')}</span></div>${project.steps.map((step,index)=>`<div class="step"><span class="step-index">0${index+1}</span><div><strong>${step.title[language]}</strong><small>${step.scope[language]}</small></div><span class="tier ${step.tier}">${t(step.tier)}</span><span class="step-check">✓</span></div>`).join('')}</div></article>`;}
function renderCharts(projects){
  const names=projects.map(p=>p.name[language]), before=projects.map(p=>p.before.durationSec/60), after=projects.map(p=>p.after.durationSec/60);
  let o=base();o.legend={bottom:0,textStyle:{color:COLORS.muted}};o.xAxis={type:'value',name:t('durationAxis'),nameTextStyle:{color:COLORS.muted},axisLabel:{color:COLORS.muted},splitLine:{lineStyle:{color:'#274936'}}};o.yAxis={type:'category',data:names,axisLabel:{color:COLORS.cream},axisTick:{show:false}};o.series=[{name:t('beforeSeries'),type:'bar',data:before,itemStyle:{color:COLORS.cream,borderRadius:[0,5,5,0]}},{name:t('afterSeries'),type:'bar',data:after,itemStyle:{color:COLORS.lime,borderRadius:[0,5,5,0]}}];chart('time-comparison',o);
  o=base();o.grid={left:55,right:30,top:30,bottom:50,containLabel:true};o.xAxis={type:'value',name:t('costAxis'),nameLocation:'middle',nameGap:30,nameTextStyle:{color:COLORS.muted,fontSize:10},axisLabel:{color:COLORS.muted},splitLine:{lineStyle:{color:'#274936'}}};o.yAxis={type:'value',name:t('durationAxis'),nameLocation:'middle',nameGap:36,nameTextStyle:{color:COLORS.muted,fontSize:10},axisLabel:{color:COLORS.muted},splitLine:{lineStyle:{color:'#274936'}}};o.series=[{type:'scatter',symbolSize:16,data:projects.flatMap(p=>[{name:`${p.name[language]} · ${t('before')}`,value:[p.before.costUsd,p.before.durationSec/60],itemStyle:{color:COLORS.cream}},{name:`${p.name[language]} · ${t('after')}`,value:[p.after.costUsd,p.after.durationSec/60],itemStyle:{color:COLORS.lime} }]),label:{show:true,position:'top',formatter:p=>p.data.name.split(' · ')[1],color:COLORS.cream,fontSize:10},labelLayout:{hideOverlap:true}}];chart('project-scatter',o);
  o=base();o.grid={left:112,right:24,top:24,bottom:58};o.xAxis={type:'category',data:[t('timeSaved'),t('costSaved')],axisLabel:{color:COLORS.muted}};o.yAxis={type:'category',data:names,axisLabel:{color:COLORS.cream,width:95,overflow:'truncate'},axisTick:{show:false}};o.visualMap={min:0,max:.7,calculable:false,orient:'horizontal',left:'center',bottom:0,textStyle:{color:COLORS.muted,fontSize:9},inRange:{color:['#385a40',COLORS.lime]}};o.series=[{type:'heatmap',data:projects.flatMap((p,y)=>[[0,y,1-p.after.durationSec/p.before.durationSec],[1,y,1-p.after.costUsd/p.before.costUsd]]),label:{show:true,color:COLORS.cream,formatter:p=>`${Math.round(p.value[2]*100)}%`},itemStyle:{borderColor:'#0b2a1b',borderWidth:4}}];chart('project-heat',o);
  const best=[...projects].sort((a,b)=>(a.after.costUsd/a.before.costUsd)-(b.after.costUsd/b.before.costUsd))[0], kinds={tool:COLORS.tool,fast:'#d8d3c5',balanced:COLORS.balanced,deep:COLORS.deep};o=base();o.grid={left:160,right:30,top:25,bottom:40,containLabel:true};o.xAxis={type:'value',name:t('minutes'),nameLocation:'middle',nameGap:28,nameTextStyle:{color:COLORS.muted,fontSize:10},axisLabel:{show:false},splitLine:{show:false}};o.yAxis={type:'category',data:best.steps.map(s=>s.title[language]),axisLabel:{color:COLORS.cream,width:140,overflow:'truncate'},axisTick:{show:false}};o.series=[{type:'custom',renderItem:(params,api)=>{const y=api.coord([0,api.value(0)])[1],x=api.coord([0,0])[0],w=api.size([api.value(1),0])[0],h=18;return {type:'rect',shape:{x,y:y-h/2,width:w,height:h,r:6},style:{fill:kinds[api.value(2)]}}},data:best.steps.map((s,i)=>[i,1+i*.58,s.tier]),encode:{x:1,y:0}}];chart('project-timeline',o);
}
function renderStrategyChart(){const strategies=data.strategies||[],o=base();o.grid={left:72,right:26,top:30,bottom:48,containLabel:true};o.xAxis={type:'value',axisLabel:{color:COLORS.muted,formatter:v=>`${Math.round(v/60)}m`},splitLine:{lineStyle:{color:'#274936'}}};o.yAxis={type:'category',data:strategies.map(s=>s.name[language]),axisLabel:{color:COLORS.cream},axisTick:{show:false}};const phases=[[t('modelExecution'),'modelSec',COLORS.lime],[t('toolVerification'),'toolSec',COLORS.cream],[t('switching'),'switchSec',COLORS.orange],[t('approvalWaiting'),'approvalWaitSec','#6d8d77']];o.series=phases.map(([name,key,color])=>({name,type:'bar',stack:'total',barWidth:19,itemStyle:{color,borderRadius:name===t('approvalWaiting')?[0,5,5,0]:0},data:strategies.map(s=>s[key]||0)}));o.legend={bottom:0,textStyle:{color:COLORS.muted,fontSize:10},itemWidth:11,itemHeight:11};chart('time-comparison',o);}
function render(){const projects=data.projects||[],strategies=data.strategies||[],baseline=strategies.find(s=>s.id==='fixed_deep'),router=strategies.find(s=>s.id==='router');$('overview-description').textContent=t('overviewDescription');$('overview-time').textContent=baseline&&router?`−${pct(router.durationSec,baseline.durationSec)}`:'—';$('overview-cost').textContent=baseline&&router?`−${pct(router.costUsd,baseline.costUsd)}`:'—';$('project-count').textContent=`${projects.length} ${t('projectsUsed')}`;$('project-summary-list').innerHTML=projects.map(renderSummary).join('');$('project-cards').innerHTML=projects.map(renderCard).join('');$('updated-at').textContent=language==='zh'?`数据生成：${data.generatedAt||'本地数据'} · ${t('simulated')}`:`Generated: ${data.generatedAt||'local data'} · ${t('simulated')}`;renderCharts(projects);renderStrategyChart();}
function showView(view){document.querySelectorAll('.view-panel').forEach(el=>el.classList.toggle('is-active',el.id===view));document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('is-active',el.dataset.view===view));setTimeout(()=>Object.values(charts).forEach(c=>c.resize()));}
document.querySelector('nav').addEventListener('click',event=>{const link=event.target.closest('[data-view]');if(link)showView(link.dataset.view);});document.addEventListener('click',event=>{const link=event.target.closest('[data-project]');if(!link)return;showView('projects');setTimeout(()=>$(`project-${link.dataset.project}`)?.scrollIntoView({behavior:'smooth',block:'start'}));});$('language-toggle').addEventListener('click',()=>{language=language==='zh'?'en':'zh';localStorage.setItem('model-router-language',language);applyLanguage();});window.addEventListener('resize',()=>Object.values(charts).forEach(c=>c.resize()));window.addEventListener('hashchange',()=>showView(location.hash==='#projects'?'projects':'overview'));fetch('./sample-data.json').then(response=>response.json()).then(json=>{data=json;applyLanguage();showView(location.hash==='#projects'?'projects':'overview');}).catch(()=>{$('overview-description').textContent='Unable to load local demo data.';});
